hpu_xfail_tests = {
    "unit/checkpoint/test_lr_scheduler.py::TestLRSchedulerCheckpoint::test_checkpoint_no_lr_scheduler[1-False]": "Xfail, due to SW-119561.",
    "unit/checkpoint/test_lr_scheduler.py::TestLRSchedulerCheckpoint::test_checkpoint_lr_scheduler[2-False]": "Xfail, due to SW-119561.",
    "unit/checkpoint/test_lr_scheduler.py::TestLRSchedulerCheckpoint::test_checkpoint_lr_scheduler[2-True]": "Xfail, due to SW-119561.",
    "unit/checkpoint/test_lr_scheduler.py::TestLRSchedulerCheckpoint::test_checkpoint_lr_scheduler[1-False]": "Xfail, due to SW-119561.",
    "unit/checkpoint/test_lr_scheduler.py::TestLRSchedulerCheckpoint::test_checkpoint_no_lr_scheduler[2-False]": "Xfail, due to SW-119561.",
    "unit/checkpoint/test_lr_scheduler.py::TestLRSchedulerCheckpoint::test_checkpoint_no_lr_scheduler[2-True]": "Xfail, due to SW-119561.",
    "unit/moe/test_moe.py::TestMoE::test[False-4]": "Xfail, due to SW-118980.",
    "unit/moe/test_moe.py::TestMoE::test[True-2]": "Xfail, due to SW-118980.",
    "unit/moe/test_moe.py::TestMoE::test[True-4]": "Xfail, due to SW-118980.",
    "unit/moe/test_moe.py::TestMoE::test[False-2]": "Xfail, due to SW-118980.",
    "unit/moe/test_moe.py::TestPRMoE::test[2-False]": "Xfail, due to SW-118980.",
    "unit/moe/test_moe.py::TestPRMoE::test[2-True]": "Xfail, due to SW-118980.",
    "unit/checkpoint/test_moe_checkpoint.py::TestMoECheckpoint::test_checkpoint_moe[4]": "Xfail, due to SW-118980.",
    "unit/inference/test_inference.py::TestModelTask::test[distilgpt2-text-generation-fp16-CG]": "xfail, due to SW-110925.",
    "unit/inference/test_inference.py::TestModelTask::test[gpt2-text-generation-fp16-noCG]": "xfail, due to SW-110925.",
    "unit/inference/test_inference.py::TestModelTask::test[distilgpt2-text-generation-fp16-noCG]": "xfail, due to SW-110925.",
    "unit/inference/test_inference.py::TestModelTask::test[gpt2-text-generation-fp16-CG]": "xfail, due to SW-110925.",
    "unit/ops/adam/test_adamw.py::TestAdamConfigs::test[AdamW-False-True-False-resulting_optimizer1]": "Xfail, due to SW-123112.",
    "unit/ops/adam/test_adamw.py::TestAdamConfigs::test[AdamW-False-True-True-resulting_optimizer5]": "Xfail, due to SW-123112.",
    "unit/ops/adam/test_adamw.py::TestAdamConfigs::test[Adam-False-True-True-resulting_optimizer13]": "Xfail, due to SW-123112.",
    "unit/ops/adam/test_adamw.py::TestAdamConfigs::test[Adam-False-True-False-resulting_optimizer9]": "Xfail, due to SW-123112.",
    "unit/ops/adam/test_adamw.py::TestAdamConfigs::test[AdamW-True-True-False-resulting_optimizer3]": "Xfail, due to SW-123112.",
    "unit/ops/adam/test_adamw.py::TestAdamConfigs::test[AdamW-True-True-True-resulting_optimizer7]": "Xfail, due to SW-123112.",
    "unit/ops/adam/test_adamw.py::TestAdamConfigs::test[Adam-True-True-True-resulting_optimizer15]": "Xfail, due to SW-123112.",
    "unit/ops/adam/test_adamw.py::TestAdamConfigs::test[Adam-True-True-False-resulting_optimizer11]": "Xfail, due to SW-123112.",
    "unit/runtime/zero/test_ignore_unused_parameters.py::TestStage2IgnoreUnusedParameters::test[False]": "Xfail, due to SW-123112.",
    "unit/runtime/zero/test_ignore_unused_parameters.py::TestStage2IgnoreUnusedParameters::test[True]": "Xfail, due to SW-123112.",
    "unit/runtime/zero/test_zero.py::TestZeroOffloadStage1::test": "Xfail, due to SW-123112.",
    "unit/runtime/half_precision/test_bf16.py::TestZeroEmptyPartition::test": "Xfail, due to SW-123112.",
    "unit/runtime/half_precision/test_bf16.py::TestZero2ReduceScatterOff::test": "Xfail, due to SW-123112.",
    "unit/runtime/zero/test_zero.py::TestIncorectAllgatherBucketSize::test[1000]": "Xfail, due to SW-123112.",
    "unit/runtime/zero/test_zero.py::TestZeroUnbalancedGradients::test[2]": "Xfail, due to SW-123112.",
    "unit/runtime/zero/test_zero.py::TestZeroUnbalancedGradients::test[1]": "Xfail, due to SW-123112.",
    "unit/runtime/zero/test_zero.py::TestPartitionNcclAlignment::test": "Xfail, due to SW-123112.",
    "unit/runtime/zero/test_zero.py::TestZeroAdamOptimizerStepCount::test[1]": "Xfail, due to SW-123112.",
    "unit/runtime/zero/test_zero.py::TestZeroAdamOptimizerStepCount::test[2]": "Xfail, due to SW-123112.",
    "unit/runtime/half_precision/test_bf16.py::TestZeroDtypeCocktail::test[bfp16-bfp16]": "Xfail, due to SW-123113.",
    "unit/runtime/half_precision/test_bf16.py::TestZeroDtypeCocktail::test[fp16-bfp16]": "Xfail, due to SW-123113.",
    "unit/runtime/half_precision/test_bf16.py::TestZeroDtypeCocktail::test[bfp16-fp32]": "Xfail, due to SW-123113.",
    "unit/runtime/half_precision/test_bf16.py::TestZeroDtypeCocktail::test[fp16-fp32]": "Xfail, due to SW-123113.",
    "unit/runtime/half_precision/test_bf16.py::TestZeroSupportedClientOptimizer::test[Adam]": "Xfail, due to SW-123113.",
    "unit/runtime/half_precision/test_bf16.py::TestZeroEmptyGrad::test": "Xfail, due to SW-123113.",
    "unit/runtime/test_ds_initialize.py::TestOptimizerImplementation::test[fp32-fp32-zero]": "Xfail, due to SW-123113.",
    "unit/runtime/test_ds_initialize.py::TestOptimizerImplementation::test[None-bf16-None]": "Xfail, due to SW-123113.",
    "unit/runtime/test_ds_initialize.py::TestOptimizerImplementation::test[bf16-bf16-zero]": "Xfail, due to SW-123113.",
    "unit/runtime/test_ds_initialize.py::TestOptimizerImplementation::test[None-bf16-zero]": "Xfail, due to SW-123113.",
    "unit/runtime/test_ds_initialize.py::TestOptimizerImplementation::test[None-fp32-zero]": "Xfail, due to SW-123113.",
    "unit/runtime/test_ds_initialize.py::TestOptimizerImplementation::test[fp32-bf16-None]": "Xfail, due to SW-123113.",
    "unit/runtime/zero/test_zero.py::TestZeroToFP32::test_2_param_groups[2]": "Xfail, due to SW-123113.",
    "unit/checkpoint/test_zero_optimizer.py::TestZeROSaveLoadEdgeCase::test_save_before_accum_grad_is_done[2]": "Xfail, due to SW-123113.",
    "unit/checkpoint/test_zero_optimizer.py::TestZeROSaveLoadEdgeCase::test_load_immediate_save[2]": "Xfail, due to SW-123113.",
    "unit/checkpoint/test_zero_optimizer.py::TestZeROSaveLoadEdgeCase::test_load_immediate_save[1]": "Xfail, due to SW-123113.",
    "unit/checkpoint/test_zero_optimizer.py::TestZeROSaveLoadEdgeCase::test_immediate_save_load[1]": "Xfail, due to SW-123113.",
    "unit/checkpoint/test_zero_optimizer.py::TestZeROSaveLoadEdgeCase::test_immediate_save_load[2]": "Xfail, due to SW-123113.",
    "unit/checkpoint/test_zero_optimizer.py::TestZeROSaveLoadEdgeCase::test_save_before_accum_grad_is_done[1]": "Xfail, due to SW-123113.",
    "unit/checkpoint/test_zero_optimizer.py::TestZeROCheckpoint::test_load_module_only[1]": "Xfail, due to SW-123113.",
    "unit/checkpoint/test_zero_optimizer.py::TestZeROCheckpoint::test_not_load_optimizer_state[2-False-Adam]": "Xfail, due to SW-123113.",
    "unit/checkpoint/test_zero_optimizer.py::TestZeROCheckpoint::test_load_optimizer_state[2-False-Adam]": "Xfail, due to SW-123113.",
    "unit/checkpoint/test_zero_optimizer.py::TestZeROCheckpoint::test_load_optimizer_state[2-True-deepspeed_adam]": "Xfail, due to SW-123113.",
    "unit/checkpoint/test_zero_optimizer.py::TestZeROCheckpoint::test_not_load_optimizer_state[2-True-deepspeed_adam]": "Xfail, due to SW-123113.",
    "unit/checkpoint/test_zero_optimizer.py::TestZeROCheckpoint::test_load_module_only[2]": "Xfail, due to SW-123113.",
    "unit/checkpoint/test_zero_optimizer.py::TestZeROCheckpoint::test_load_optimizer_state[1-False-Adam]": "Xfail, due to SW-123113.",
    "unit/checkpoint/test_zero_optimizer.py::TestZeROCheckpoint::test_not_load_optimizer_state[1-False-Adam]": "Xfail, due to SW-123113.",
    "unit/checkpoint/test_zero_optimizer.py::TestZeROCheckpoint::test_hybrid_optimizer_state[1]": "Xfail, due to SW-123113.",
    "unit/checkpoint/test_zero_optimizer.py::TestZeROCheckpoint::test_hybrid_optimizer_state[2]": "Xfail, due to SW-123113.",
    "unit/inference/test_inference.py::TestLMCorrectness::test[lambada-gpt2-EleutherAI/gpt-neo-2.7B]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/inference/test_inference.py::TestLMCorrectness::test[lambada-gpt2-gpt2-xl]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/inference/test_inference.py::TestLMCorrectness::test[lambada-gpt2-EleutherAI/gpt-j-6B]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/inference/test_checkpoint_sharding.py::TestCheckpointShard::test[EleutherAI/gpt-j-6B-int8]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/model_parallelism/test_configurable_parallel_pp.py::TestConfigurableResizePP::test_world_size_2to4[1-2-1-4]": "Xfail, test failed on 0.7.7 vanilla version",
    "unit/model_parallelism/test_configurable_parallel_pp.py::TestConfigurableResizePP::test_world_size_2to1[1-2-1-1]": "Xfail, test failed on 0.7.7 vanilla version",
    "unit/runtime/half_precision/test_fp16.py::TestAmp::test_adam_O2_empty_grad": "Xfail, test failed on 0.7.7 vanilla version",
    "unit/runtime/zero/test_zero_context.py::test_ext_param_return": "Xfail, test failed on 0.7.7 vanilla version",
    "unit/runtime/zero/test_zero_context.py::test_ext_param_getattr": "Xfail, test failed on 0.7.7 vanilla version",
    "unit/runtime/zero/test_zero_context.py::test_stage_3_output_type[tensor]": "Xfail, test failed on 0.7.7 vanilla version",
    "unit/runtime/zero/test_zero_context.py::test_stage_3_output_type[dict]": "Xfail, test failed on 0.7.7 vanilla version",
    "unit/inference/test_checkpoint_sharding.py::TestCheckpointShard::test[EleutherAI/gpt-neo-125M-int8]": "Xfail, due to SW-123615.",
    "unit/inference/test_checkpoint_sharding.py::TestCheckpointShard::test[bigscience/bloom-560m-int8]": "Xfail, due to SW-123615.",
    "unit/inference/test_checkpoint_sharding.py::TestCheckpointShard::test[EleutherAI/gpt-j-6B-int8]": "Xfail, due to SW-123615.",
    "unit/inference/test_checkpoint_sharding.py::TestCheckpointShard::test[facebook/opt-125m-int8]": "Xfail, due to SW-123615.",
    "unit/inference/test_model_profiling.py::TestModelProfiling::test[True-False-gpt2-text-generation]": "Xfail, due to SW-110925.",
    "unit/inference/test_model_profiling.py::TestModelProfiling::test[False-False-gpt2-text-generation]": "Xfail, due to SW-110925.",
    "unit/inference/test_inference.py::TestInjectionPolicy::test[noCG-fp32-t5]": "Xfail, due to SW-123610.",
    "unit/inference/test_model_profiling.py::TestModelProfiling::test[True-False-roberta-base-fill-mask]": "Xfail, due to SW-124433",
}

g1_xfail_tests = {
}

g2_xfail_tests = {
}

gpu_xfail_tests = {
    "unit/inference/test_checkpoint_sharding.py::TestCheckpointShard::test[EleutherAI/gpt-j-6B-int8]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/inference/test_checkpoint_sharding.py::TestCheckpointShard::test[EleutherAI/gpt-j-6B-fp16]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/ops/quantizer/test_fake_quantization.py::test_fake_quant_dequant[1-tensor_shape0]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/ops/quantizer/test_fake_quantization.py::test_fake_quant_dequant[16-tensor_shape1]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/ops/quantizer/test_fake_quantization.py::test_fake_quant_dequant[1-tensor_shape1]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/ops/quantizer/test_fake_quantization.py::test_fake_quant_dequant[16-tensor_shape0]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/inference/test_inference.py::TestMPSize::test[fp16-noCG-bloom]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/inference/test_inference.py::TestMPSize::test[fp16-noCG-gpt-j]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/inference/test_inference.py::TestLMCorrectness::test[lambada-gpt2-EleutherAI/gpt-neo-2.7B]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/inference/test_inference.py::TestLMCorrectness::test[lambada-gpt2-gpt2-xl]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/inference/test_inference.py::TestLMCorrectness::test[lambada-gpt2-EleutherAI/gpt-j-6B]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/model_parallelism/test_configurable_parallel_pp.py::TestConfigurableResizePP::test_world_size_2to4[2-1-2-2]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/model_parallelism/test_configurable_parallel_pp.py::TestConfigurableResizePP::test_world_size_1to4[1-1-2-2]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/model_parallelism/test_configurable_parallel_pp.py::TestConfigurableResizePP::test_world_size_2to1[1-2-1-1]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/model_parallelism/test_configurable_parallel_pp.py::TestConfigurableResizePP::test_world_size_2to4[1-2-1-4]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/runtime/half_precision/test_fp16.py::TestAmp::test_adam_O2_empty_grad": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/runtime/zero/test_zero_context.py::test_ext_param_getattr": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/runtime/zero/test_zero_context.py::test_ext_param_return": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/runtime/zero/test_zero_context.py::test_stage_3_output_type[dict]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/runtime/zero/test_zero_context.py::test_stage_3_output_type[tensor]": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/runtime/zero/test_zero_context.py::TestGatherUpdate::test": "Xfail, test failed on 0.7.7 vanilla version on GPU.",
    "unit/checkpoint/test_moe_checkpoint.py::TestMoECheckpoint::test_checkpoint_moe_and_zero[2-True]": "Xfail, due to SW-123291",
    "unit/checkpoint/test_moe_checkpoint.py::TestMoECheckpoint::test_checkpoint_moe_and_zero[2-False]": "Xfail, due to SW-123291",
    "unit/checkpoint/test_moe_checkpoint.py::TestMoECheckpoint::test_checkpoint_moe_and_zero[4-False]": "Xfail, due to SW-123291",
    "unit/checkpoint/test_moe_checkpoint.py::TestMoECheckpoint::test_checkpoint_moe_and_zero[4-True]": "Xfail, due to SW-123291"
}
